'use client';
import { useState } from "react";
import { getDeviceFingerprint } from "./lib/fingerprint";

export default function Home() {
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [pricingTab, setPricingTab] = useState('creators');
  const [creatorBilling, setCreatorBilling] = useState('monthly');
  const [ecomBilling, setEcomBilling] = useState('monthly');
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [prompt, setPrompt] = useState("");
  const [expandedPrompt, setExpandedPrompt] = useState("");
  const [promptLoading, setPromptLoading] = useState(false);
  const [activeNiche, setActiveNiche] = useState(0);

  const handleSubmit = async () => {
    if (!email) return;
    setLoading(true);
    setError("");
    try {
      const fingerprint = await getDeviceFingerprint();
      const res = await fetch('/api/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, fingerprint })
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || 'Something went wrong.');
      } else {
        setSubmitted(true);
      }
    } catch (err) {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handlePromptExpand = async () => {
    if (!prompt) return;
    setPromptLoading(true);
    setExpandedPrompt("");
    await new Promise(r => setTimeout(r, 1500));
    setExpandedPrompt(`Cinematic 4K shot. ${prompt}. Volumetric golden hour lighting, anamorphic 35mm lens, f/1.8 aperture. Slow orbital camera movement at 60fps. Ray-traced shadows with atmospheric depth. Professional color grade, film grain overlay. Ultra-realistic textures with shallow depth of field. Generated by KlipflowAI Director Engine.`);
    setPromptLoading(false);
  };

  const niches = [
    { name: "😱 Scary Stories", script: "In a small town with no name, the lights went out every night at exactly 3am. No one talked about it. Until she moved in...", views: "847K views" },
    { name: "💰 Finance & Wealth", script: "The #1 mistake people make with their first $10,000. I wish someone told me this at 22. Here's what the wealthy actually do differently...", views: "1.2M views" },
    { name: "🏋️ Fitness", script: "I lost 30 pounds in 90 days without going to the gym once. Here's the exact system I used — and it takes 10 minutes a day...", views: "623K views" },
    { name: "🌟 Motivation", script: "The most successful people in the world all share one habit. It's not waking up at 5am. It's not cold showers. It's something much simpler...", views: "2.1M views" },
    { name: "💎 Luxury", script: "Inside the $50 million penthouse that nobody talks about. The rooftop. The private elevator. The view that changes everything...", views: "934K views" },
    { name: "🤖 AI & Tech", script: "This AI tool just made 10 professions completely obsolete. And nobody is talking about the one job it can't replace...", views: "1.8M views" }
  ];

  const ecomPlans = [
    {
      name: "Starter",
      monthly: "$49", sixmonths: "$42", yearly: "$39",
      desc: "Perfect for small e-com brands",
      features: [
        "All 9 AI modules included",
        "Facebook Ad Spy Radar",
        "AI Image & Video Ad Generator",
        "AI Actor Generator",
        "Upload your own actor",
        "UGC Avatar videos",
        "Voice generation",
        "One-Click Ad Launcher",
        "1 ad account",
        "Standard processing",
        "Email support"
      ],
      highlight: false
    },
    {
      name: "Pro",
      monthly: "$149", sixmonths: "$129", yearly: "$119",
      desc: "For serious brand builders",
      features: [
        "Everything in Starter +",
        "5 ad accounts",
        "A/B creative testing",
        "Priority processing speed",
        "Priority support"
      ],
      highlight: true
    },
    {
      name: "Agency",
      monthly: "$499", sixmonths: "$429", yearly: "$399",
      desc: "For agencies and large teams",
      features: [
        "Everything in Pro +",
        "Unlimited ad accounts",
        "Ultra priority processing",
        "White label ready",
        "Full API access",
        "Team member seats",
        "Custom onboarding",
        "Dedicated account manager"
      ],
      highlight: false
    }
  ];

  const getEcomPrice = (plan: typeof ecomPlans[0]) => {
    if (ecomBilling === 'monthly') return plan.monthly;
    if (ecomBilling === 'sixmonths') return plan.sixmonths;
    return plan.yearly;
  };

  const ecomSavings: Record<string, string> = {
    monthly: '', sixmonths: 'Save 14%', yearly: 'Save 20%'
  };

  const faqs = [
    { q: "What is KlipflowAI?", a: "KlipflowAI is an all-in-one AI platform for content creators and e-commerce brands. It combines Facebook Ad Spy, AI video and image generation, script writing, voice synthesis, avatar creation, automated social posting across 5 platforms, and one-click ad launching — all in one place." },
    { q: "How does the AI Employee work for creators?", a: "You pick your niche and posting frequency once. KlipflowAI then automatically finds trending topics in your niche, writes the script, generates the visuals, adds a voiceover, and posts to TikTok, Instagram, YouTube, Facebook, and X on your schedule. You literally just check in to see your growth." },
    { q: "Which platforms does auto-posting support?", a: "TikTok, Instagram, YouTube Shorts, Facebook, and X (Twitter). That's 5 platforms — more than any competitor on the market." },
    { q: "What types of content can I create?", a: "Text-to-video, image-to-video, AI actor videos, UGC testimonial videos, AI image ads, script-to-video with voiceover, and more. Every format you need for social media and advertising." },
    { q: "Do free trial videos have a watermark?", a: "Yes. Your 25 free trial tokens generate watermarked videos so you can experience the full quality before committing. The watermark disappears automatically the moment you subscribe to any paid plan." },
    { q: "What are tokens?", a: "Tokens are your generation credits. 1 video = 10 tokens, 1 image = 2 tokens. Every signup gets 25 free tokens — enough for 2 full videos. Top up anytime from $5 inside your dashboard." },
    { q: "Is the Facebook Ad Spy legal?", a: "Yes. We use Meta's official Ads Library API which is publicly available and fully compliant with Meta's terms of service. No scraping, no violations." },
    { q: "Can I upload my own actor for videos?", a: "Yes. Upload a photo of your talent and generate AI videos using their likeness. You'll confirm you own the rights to the image before generating." },
    { q: "How is KlipflowAI different from other AI video tools?", a: "KlipflowAI is the only platform that combines ad intelligence, AI video and image generation, script writing, voice synthesis, avatar creation, automated 5-platform posting, AND one-click ad launching. Competitors only do one or two of these things." },
    { q: "How fast is video generation?", a: "Standard videos generate in 1-3 minutes. Pro and Agency plan users get priority processing, typically under 60 seconds." },
    { q: "Can I cancel anytime?", a: "Absolutely. No contracts, no hidden fees. Cancel with one click from your dashboard and you'll never be charged again." },
    { q: "Is KlipflowAI suitable for beginners?", a: "Yes. If you can pick a niche and type a sentence, you can use KlipflowAI. No video editing, no design skills, no technical knowledge required whatsoever." }
  ];

  return (
    <main className="min-h-screen bg-black text-white">

      {/* NAV */}
      <nav className="flex items-center justify-between px-8 py-5 border-b border-white/10 sticky top-0 z-50 bg-black/90 backdrop-blur-md">
        <span className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
          KlipflowAI
        </span>
        <div className="hidden md:flex gap-8 text-gray-400 text-sm">
          <a href="#creator" className="hover:text-white transition">For Creators</a>
          <a href="#ecom" className="hover:text-white transition">For Brands</a>
          <a href="#features" className="hover:text-white transition">Features</a>
          <a href="#pricing" className="hover:text-white transition">Pricing</a>
          <a href="#faq" className="hover:text-white transition">FAQ</a>
        </div>
        <div className="flex items-center gap-3">
          <button className="text-gray-400 hover:text-white text-sm font-semibold py-2 px-5 rounded-full border border-white/20 hover:border-white/40 transition">
            Sign In
          </button>
          <button className="bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold py-2 px-5 rounded-full transition">
            Sign Up Free
          </button>
        </div>
      </nav>

      {/* HERO */}
      <section className="flex flex-col items-center justify-center text-center px-4 py-28">
        <div className="inline-block bg-purple-900/40 border border-purple-500/30 text-purple-300 text-xs font-semibold px-4 py-1.5 rounded-full mb-6">
          🚀 The Only Platform That Spies, Creates & Launches — All in One
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold mb-6 leading-tight">
          Spy. Generate. <br />
          <span className="bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
            Dominate.
          </span>
        </h1>
        <div className="flex flex-col gap-4 max-w-2xl mb-10 text-center">
          <p className="text-lg md:text-xl text-gray-400">
            <span className="text-purple-400 font-semibold">For Brands:</span> Spy on winning Facebook ads, generate better ones, and launch campaigns in minutes.
          </p>
          <p className="text-lg md:text-xl text-gray-400">
            <span className="text-pink-400 font-semibold">For Creators:</span> Pick your niche. Your AI employee writes scripts, generates videos, adds voiceover, and posts to 5 platforms — automatically.
          </p>
        </div>

        {!submitted ? (
          <div className="flex flex-col items-center w-full max-w-md gap-3">
            <div className="flex flex-col sm:flex-row gap-3 w-full">
              <input
                type="email"
                placeholder="Enter your email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="flex-1 bg-white/10 border border-white/20 rounded-full px-6 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500"
              />
              <button
                onClick={handleSubmit}
                disabled={loading}
                className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 px-8 rounded-full transition disabled:opacity-50"
              >
                {loading ? 'Please wait...' : 'Sign Up Free'}
              </button>
            </div>
            {error && <p className="text-red-400 text-sm">{error}</p>}
          </div>
        ) : (
          <div className="bg-purple-900/40 border border-purple-500/30 text-purple-300 px-8 py-4 rounded-full text-lg font-semibold">
            🎉 Check your email to verify your account and claim your 25 free tokens!
          </div>
        )}
        <p className="text-gray-600 text-xs mt-4">No credit card required · 25 free tokens on signup · Cancel anytime</p>

        <div className="grid grid-cols-3 gap-12 mt-16 max-w-2xl mx-auto">
          {[
            { stat: "5", label: "Platforms Auto-Posted To" },
            { stat: "$0", label: "To Start Today" },
            { stat: "9", label: "Powerful AI Modules" }
          ].map((s, i) => (
            <div key={i} className="text-center">
              <div className="text-4xl font-extrabold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">{s.stat}</div>
              <div className="text-gray-500 text-sm mt-1">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* AI EMPLOYEE SECTION - CREATORS */}
      <section id="creator" className="px-8 py-24 bg-gradient-to-b from-purple-950/30 to-black">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-block bg-purple-900/40 border border-purple-500/30 text-purple-300 text-xs font-semibold px-4 py-1.5 rounded-full mb-4">
              🤖 For Content Creators
            </div>
            <h2 className="text-4xl md:text-5xl font-extrabold mb-6">
              Your AI Employee.<br />
              <span className="bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">You Just Pick the Niche.</span>
            </h2>
            <p className="text-gray-400 text-xl max-w-2xl mx-auto">
              KlipflowAI writes the scripts, generates the visuals, adds the voiceover, and posts to 5 platforms on autopilot. You check in. The page grows.
            </p>
          </div>

          {/* ZERO TOUCH LOOP */}
          <div className="grid md:grid-cols-5 gap-4 mb-20">
            {[
              { step: "1", icon: "🎯", title: "Pick Niche", desc: "Choose your content niche once" },
              { step: "2", icon: "✍️", title: "AI Writes Script", desc: "Trending hooks & stories auto-generated" },
              { step: "3", icon: "🎬", title: "AI Generates Video", desc: "Cinematic visuals created automatically" },
              { step: "4", icon: "🎙️", title: "AI Adds Voice", desc: "Natural voiceover synced perfectly" },
              { step: "5", icon: "📡", title: "Auto-Posted", desc: "Live on 5 platforms on schedule" }
            ].map((s, i) => (
              <div key={i} className="relative">
                <div className="bg-white/5 border border-white/10 rounded-2xl p-5 text-center hover:border-purple-500/50 transition h-full">
                  <div className="text-3xl mb-2">{s.icon}</div>
                  <div className="text-purple-400 text-xs font-bold mb-1">Step {s.step}</div>
                  <div className="font-bold text-sm mb-1">{s.title}</div>
                  <div className="text-gray-500 text-xs">{s.desc}</div>
                </div>
                {i < 4 && (
                  <div className="hidden md:block absolute top-1/2 -right-3 text-purple-500 text-lg z-10">→</div>
                )}
              </div>
            ))}
          </div>

          {/* NICHE SELECTOR DEMO */}
          <div className="bg-black border border-white/10 rounded-3xl p-8 mb-12">
            <div className="text-center mb-8">
              <h3 className="text-2xl font-bold mb-2">Pick a Niche. Watch the Magic.</h3>
              <p className="text-gray-400 text-sm">See what your AI employee would create for each niche</p>
            </div>
            <div className="flex flex-wrap gap-3 justify-center mb-8">
              {niches.map((niche, i) => (
                <button
                  key={i}
                  onClick={() => setActiveNiche(i)}
                  className={`px-4 py-2 rounded-full text-sm font-semibold transition ${activeNiche === i ? 'bg-purple-600 text-white' : 'bg-white/10 text-gray-400 hover:text-white'}`}
                >
                  {niche.name}
                </button>
              ))}
            </div>
            <div className="bg-white/5 border border-purple-500/20 rounded-2xl p-6 max-w-2xl mx-auto">
              <div className="flex items-center justify-between mb-4">
                <div className="text-purple-400 text-xs font-bold uppercase tracking-widest">AI Generated Script Hook</div>
                <div className="bg-green-900/40 border border-green-500/30 text-green-400 text-xs font-bold px-3 py-1 rounded-full">{niches[activeNiche].views}</div>
              </div>
              <p className="text-white text-sm leading-relaxed italic">"{niches[activeNiche].script}"</p>
              <div className="mt-4 flex items-center gap-2 text-gray-500 text-xs">
                <span>⚡ Generated in seconds</span>
                <span>·</span>
                <span>🎬 Video auto-created</span>
                <span>·</span>
                <span>📡 Posted to 5 platforms</span>
              </div>
            </div>
          </div>

          {/* 5 PLATFORMS */}
          <div className="text-center">
            <h3 className="text-2xl font-bold mb-3">Posted to 5 Platforms. Automatically.</h3>
            <p className="text-gray-400 text-sm mb-8">Your content goes everywhere while you sleep.</p>
            <div className="flex justify-center gap-6 flex-wrap">
              {[
                { name: "TikTok", icon: "🎵", color: "from-pink-500 to-red-500" },
                { name: "Instagram", icon: "📸", color: "from-purple-500 to-pink-500" },
                { name: "YouTube", icon: "▶️", color: "from-red-600 to-red-400" },
                { name: "Facebook", icon: "👥", color: "from-blue-600 to-blue-400" },
                { name: "X", icon: "𝕏", color: "from-gray-600 to-gray-400" }
              ].map((p, i) => (
                <div key={i} className="flex flex-col items-center gap-2">
                  <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${p.color} flex items-center justify-center text-2xl shadow-lg`}>
                    {p.icon}
                  </div>
                  <span className="text-gray-400 text-xs font-semibold">{p.name}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* LIVE DEMO */}
      <section className="px-8 py-20 bg-white/5">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold text-center mb-4">Try Our Prompt Engine — Free</h2>
          <p className="text-gray-400 text-center mb-12">Type a simple idea. Watch our AI Director transform it into a cinematic prompt instantly.</p>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-black border border-white/10 rounded-2xl p-6">
              <div className="text-purple-400 text-xs font-bold uppercase tracking-widest mb-3">Your Simple Idea</div>
              <textarea
                placeholder='e.g. "Luxury watch on a rocky mountain at sunset"'
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-600 focus:outline-none focus:border-purple-500 resize-none h-32 text-sm"
              />
              <button
                onClick={handlePromptExpand}
                disabled={promptLoading || !prompt}
                className="mt-4 w-full bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white font-bold py-3 rounded-full transition"
              >
                {promptLoading ? '✨ Expanding...' : '✨ Expand with AI Director'}
              </button>
            </div>
            <div className="bg-black border border-white/10 rounded-2xl p-6">
              <div className="text-pink-400 text-xs font-bold uppercase tracking-widest mb-3">Cinematic Prompt Output</div>
              {expandedPrompt ? (
                <p className="text-gray-300 text-sm leading-relaxed">{expandedPrompt}</p>
              ) : (
                <div className="h-32 flex items-center justify-center text-gray-600 text-sm">
                  Your cinematic prompt will appear here...
                </div>
              )}
              {expandedPrompt && (
                <div className="mt-4 bg-purple-900/30 border border-purple-500/30 rounded-xl p-3 text-xs text-purple-300">
                  ⚡ Sign up free to use this prompt to generate a full AI video
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* ECOM SECTION */}
      <section id="ecom" className="px-8 py-24 bg-gradient-to-b from-black to-pink-950/20">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-block bg-pink-900/40 border border-pink-500/30 text-pink-300 text-xs font-semibold px-4 py-1.5 rounded-full mb-4">
              🛍️ For E-Commerce Brands
            </div>
            <h2 className="text-4xl md:text-5xl font-extrabold mb-6">
              Spy. Create. Launch.<br />
              <span className="bg-gradient-to-r from-pink-400 to-purple-500 bg-clip-text text-transparent">In Under 5 Minutes.</span>
            </h2>
            <p className="text-gray-400 text-xl max-w-2xl mx-auto">
              Find what's already working in your market. Generate a better version. Launch it to Facebook Ads automatically. No agency. No editor. No waiting.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: "🕵️",
                title: "Spy on Winners",
                desc: "Find Facebook ads that have been running profitably for 7+ days. Filter by niche, format, and market. One click to remix any winning ad into your own.",
                badge: "Legal & Official"
              },
              {
                icon: "🎨",
                title: "Generate Better Ads",
                desc: "Our AI generates video ads, image ads, and UGC testimonials — all inspired by winning formulas but completely unique to your brand.",
                badge: "Video + Image + UGC"
              },
              {
                icon: "🚀",
                title: "Launch in One Click",
                desc: "Answer 5 quick questions about your audience and budget. KlipflowAI picks the best creative and launches your Facebook campaign automatically.",
                badge: "No Ad Manager Needed"
              }
            ].map((f, i) => (
              <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-8 hover:border-pink-500/50 transition">
                <div className="text-4xl mb-4">{f.icon}</div>
                <div className="inline-block bg-pink-900/30 border border-pink-500/20 text-pink-300 text-xs font-bold px-3 py-1 rounded-full mb-3">{f.badge}</div>
                <h3 className="text-xl font-bold mb-3">{f.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHY KLIPFLOWAI */}
      <section className="px-8 py-24 max-w-6xl mx-auto">
        <h2 className="text-4xl font-bold text-center mb-4">Why Choose KlipflowAI</h2>
        <p className="text-gray-400 text-center mb-16">The most complete AI content and advertising platform ever built.</p>
        <div className="grid md:grid-cols-3 gap-8">
          {[
            { icon: "💰", title: "Built for Revenue", desc: "Every feature is designed to help you make money — whether you're running ads, growing a faceless channel, or selling products. This isn't just a video tool, it's a revenue engine." },
            { icon: "⚡", title: "From Idea to Live in Minutes", desc: "Spy a winning ad, generate a better version, and launch your campaign — all in under 5 minutes. No agencies, no editors, no waiting. Just results." },
            { icon: "🔄", title: "Fully Closed Loop", desc: "Unlike other tools that do one thing, KlipflowAI handles the entire workflow: research → create → distribute → analyze. Set it once and let it run." }
          ].map((f, i) => (
            <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-8 text-center hover:border-purple-500/50 transition">
              <div className="text-5xl mb-4">{f.icon}</div>
              <h3 className="text-xl font-bold mb-3">{f.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="px-8 py-24 bg-white/5">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-4xl font-bold text-center mb-4">How It Works</h2>
          <p className="text-gray-400 text-center mb-16">Three steps to dominate your market.</p>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "01", icon: "🕵️", title: "Spy & Discover", desc: "Find winning Facebook ads running 7+ days. One click to remix any winning formula into your own campaign.", color: "from-purple-600 to-purple-400" },
              { step: "02", icon: "🎬", title: "Generate & Create", desc: "AI writes your script, generates cinematic video or image ads, and adds professional voiceover — automatically.", color: "from-pink-600 to-purple-500" },
              { step: "03", icon: "🚀", title: "Launch & Automate", desc: "Brands launch Facebook campaigns in one click. Creators set autopilot and content posts to 5 platforms daily.", color: "from-pink-500 to-pink-400" }
            ].map((s, i) => (
              <div key={i} className="bg-black border border-white/10 rounded-2xl p-8 hover:border-purple-500/50 transition">
                <div className={`text-5xl font-extrabold bg-gradient-to-r ${s.color} bg-clip-text text-transparent mb-4`}>{s.step}</div>
                <div className="text-3xl mb-3">{s.icon}</div>
                <h3 className="text-xl font-bold mb-3">{s.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES GRID */}
      <section id="features" className="px-8 py-24 max-w-6xl mx-auto">
        <h2 className="text-4xl font-bold text-center mb-4">9 Powerful Modules. One Platform.</h2>
        <p className="text-gray-400 text-center mb-16">Every tool you need. Every plan includes everything.</p>
        <div className="grid md:grid-cols-3 gap-8">
          {[
            { icon: "🕵️", title: "Facebook Ad Spy Radar", desc: "Monitor winning Facebook ads in real time. Filter by niche, duration, and format. See what's scaling before you spend a dollar." },
            { icon: "✍️", title: "AI Script Writer", desc: "Our AI writes trending hooks, full scripts, and CTAs based on your niche. Updated daily with what's going viral right now." },
            { icon: "🎬", title: "Text to Video", desc: "Type any idea and our cinematic prompt engine produces a professional AI video. Choose from Kling, Veo 3, or Sora." },
            { icon: "🖼️", title: "Image to Video", desc: "Animate any still image into a stunning video. Perfect for product shots and lifestyle images. Control motion and speed." },
            { icon: "🧑‍🎤", title: "AI Actor Generator", desc: "Describe your ideal spokesperson and our AI generates a photorealistic human avatar. Save and reuse across unlimited videos." },
            { icon: "📸", title: "Upload Your Own Actor", desc: "Use your own talent. Upload a photo and generate AI videos using their likeness. Comes with consent verification." },
            { icon: "🎙️", title: "AI Voice Generation", desc: "Generate natural voiceovers synced to your avatar or video. Multiple voice styles, accents, and tones." },
            { icon: "🤖", title: "Content Autopilot", desc: "Set daily posting rules once. KlipflowAI posts to TikTok, Instagram, YouTube, Facebook, and X automatically every day." },
            { icon: "🚀", title: "One-Click Ad Launcher", desc: "Answer 5 questions about your audience and budget. AI selects the best creative and launches your Facebook campaign automatically." }
          ].map((f, i) => (
            <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-8 hover:border-purple-500/50 transition">
              <div className="text-4xl mb-4">{f.icon}</div>
              <h3 className="text-xl font-bold mb-3">{f.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* WATERMARK NOTICE */}
      <section className="px-8 py-6 max-w-4xl mx-auto">
        <div className="bg-purple-900/20 border border-purple-500/20 rounded-2xl p-6 flex flex-col md:flex-row items-center gap-4 text-center md:text-left">
          <div className="text-4xl">🎁</div>
          <div>
            <h3 className="font-bold text-white mb-1">Try Before You Subscribe</h3>
            <p className="text-gray-400 text-sm">Your 25 free tokens generate watermarked videos so you can see the full quality before committing. The watermark disappears automatically the moment you subscribe to any paid plan.</p>
          </div>
        </div>
      </section>

      {/* COMPARISON TABLE */}
      <section className="px-8 py-24 max-w-5xl mx-auto">
        <h2 className="text-4xl font-bold text-center mb-4">KlipflowAI vs The Rest</h2>
        <p className="text-gray-400 text-center mb-16">No other platform comes close to this feature set.</p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-4 px-4 text-gray-400 font-semibold">Feature</th>
                <th className="py-4 px-4 text-purple-400 font-bold text-center">KlipflowAI</th>
                <th className="py-4 px-4 text-gray-500 font-semibold text-center">Other Tools</th>
                <th className="py-4 px-4 text-gray-500 font-semibold text-center">Ad Spy Tools</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["AI Script Writer", true, true, false],
                ["AI Video Generation", true, true, false],
                ["Image to Video", true, true, false],
                ["AI Actor Generator", true, false, false],
                ["Upload Own Actor", true, false, false],
                ["AI Voice Generation", true, true, false],
                ["UGC Avatar Videos", true, false, false],
                ["Facebook Ad Spy", true, false, true],
                ["AI Image Ad Generator", true, false, false],
                ["One-Click Ad Launcher", true, false, false],
                ["Auto-Post to 5 Platforms", true, false, false],
                ["TikTok Auto-Posting", true, true, false],
                ["Token Top-Up from $5", true, false, false],
              ].map(([feature, us, content, adspy], i) => (
                <tr key={i} className="border-b border-white/5 hover:bg-white/3 transition">
                  <td className="py-4 px-4 text-gray-300">{feature as string}</td>
                  <td className="py-4 px-4 text-center">{us ? <span className="text-purple-400 font-bold text-lg">✓</span> : <span className="text-gray-600">✗</span>}</td>
                  <td className="py-4 px-4 text-center">{content ? <span className="text-green-400 font-bold text-lg">✓</span> : <span className="text-gray-600">✗</span>}</td>
                  <td className="py-4 px-4 text-center">{adspy ? <span className="text-green-400 font-bold text-lg">✓</span> : <span className="text-gray-600">✗</span>}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* SOCIAL PROOF */}
      <section className="px-8 py-24 bg-white/5">
        <h2 className="text-4xl font-bold text-center mb-4">Loved by Creators & Brands</h2>
        <p className="text-gray-400 text-center mb-16">Join thousands of marketers already using KlipflowAI.</p>
        <div className="grid md:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {[
            { name: "Sarah K.", handle: "@sarahkreates", avatar: "SK", text: "I went from spending $3,000/month on video editors to generating 30 videos a week with KlipflowAI. The autopilot posts to all 5 platforms while I sleep. Insane.", role: "Faceless Channel Creator" },
            { name: "Marcus T.", handle: "@marcustrades", avatar: "MT", text: "The Ad Spy tool found me a winning product in 20 minutes. I generated the ad, launched it, and made $4,200 in my first week. This platform is a cheat code.", role: "E-Commerce Brand Owner" },
            { name: "Priya M.", handle: "@priyamedia", avatar: "PM", text: "Managing 8 client accounts used to take my whole team. KlipflowAI handles content across all platforms and my team focuses on strategy. Complete game changer.", role: "Digital Marketing Agency" }
          ].map((t, i) => (
            <div key={i} className="bg-black border border-white/10 rounded-2xl p-6 hover:border-purple-500/30 transition">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-full bg-purple-600 flex items-center justify-center text-sm font-bold">{t.avatar}</div>
                <div>
                  <div className="font-semibold text-sm">{t.name}</div>
                  <div className="text-gray-500 text-xs">{t.handle}</div>
                </div>
              </div>
              <p className="text-gray-300 text-sm leading-relaxed mb-4">"{t.text}"</p>
              <div className="text-purple-400 text xs font-semibold">{t.role}</div>
            </div>
          ))}
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="px-8 py-24">
        <h2 className="text-4xl font-bold text-center mb-4">Simple, Transparent Pricing</h2>
        <p className="text-gray-400 text-center mb-10">All features included on every plan. Only volume changes.</p>

        <div className="flex justify-center mb-12">
          <div className="bg-white/10 rounded-full p-1 flex gap-1">
            <button onClick={() => setPricingTab('creators')} className={`px-8 py-2.5 rounded-full font-semibold text-sm transition ${pricingTab === 'creators' ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'}`}>
              For Creators
            </button>
            <button onClick={() => setPricingTab('ecom')} className={`px-8 py-2.5 rounded-full font-semibold text-sm transition ${pricingTab === 'ecom' ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'}`}>
              For E-Commerce
            </button>
          </div>
        </div>

        {pricingTab === 'creators' && (
          <div className="max-w-5xl mx-auto">
            <div className="flex justify-center items-center gap-4 mb-12">
              <span className={`text-sm font-semibold ${creatorBilling === 'monthly' ? 'text-white' : 'text-gray-500'}`}>Monthly</span>
              <button onClick={() => setCreatorBilling(creatorBilling === 'monthly' ? 'yearly' : 'monthly')} className="relative w-12 h-6 bg-purple-600 rounded-full transition">
                <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${creatorBilling === 'yearly' ? 'left-7' : 'left-1'}`} />
              </button>
              <span className={`text-sm font-semibold ${creatorBilling === 'yearly' ? 'text-white' : 'text-gray-500'}`}>
                Yearly <span className="text-purple-400 text-xs">(Save up to 24%)</span>
              </span>
            </div>

            <div className="bg-purple-900/20 border border-purple-500/30 rounded-2xl p-6 flex flex-col md:flex-row items-center justify-between mb-8 gap-4">
              <div>
                <h3 className="text-lg font-bold text-purple-300 mb-1">🎁 Free Trial — No Credit Card Required</h3>
                <p className="text-gray-400 text-sm">Sign up and get 25 free tokens instantly. Generate your first 2 watermarked videos completely free.</p>
              </div>
              <button className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 px-8 rounded-full transition whitespace-nowrap">
                Sign Up Free
              </button>
            </div>

            <div className="grid md:grid-cols-2 gap-8 max-w-3xl mx-auto">
              {[
                {
                  name: "Starter", monthly: "$29", yearly: "$23",
                  desc: "Perfect for solo creators",
                  tokens: "250 tokens/month (~25 videos)",
                  features: ["All 9 AI modules included", "AI Script Writer", "250 tokens per month", "Watermark-free videos", "Auto-post to 5 platforms", "3 social accounts connected", "Standard processing", "Email support"],
                  highlight: false
                },
                {
                  name: "Pro", monthly: "$59", yearly: "$45",
                  desc: "For serious content creators",
                  tokens: "500 tokens/month (~50 videos)",
                  features: ["All 9 AI modules included", "AI Script Writer", "500 tokens per month", "Watermark-free videos", "Auto-post to 5 platforms", "10 social accounts connected", "Full autopilot automation", "Priority processing speed", "Early access to new features", "Priority support"],
                  highlight: true
                }
              ].map((plan, i) => (
                <div key={i} className={`rounded-2xl p-8 border ${plan.highlight ? "border-purple-500 bg-purple-900/20" : "border-white/10 bg-white/5"}`}>
                  {plan.highlight && <div className="text-xs font-bold text-purple-400 mb-3 uppercase tracking-widest">Most Popular</div>}
                  <h3 className="text-2xl font-bold mb-1">{plan.name}</h3>
                  <p className="text-gray-400 text-sm mb-4">{plan.desc}</p>
                  <div className="text-5xl font-extrabold mb-1">
                    {creatorBilling === 'monthly' ? plan.monthly : plan.yearly}
                    <span className="text-lg text-gray-400">/mo</span>
                  </div>
                  {creatorBilling === 'yearly' && <p className="text-purple-400 text-xs mb-4">Billed annually</p>}
                  <p className="text-purple-300 text-sm font-semibold mb-6">{plan.tokens}</p>
                  <ul className="space-y-3 mb-8">
                    {plan.features.map((f, j) => (
                      <li key={j} className="flex items-center gap-2 text-sm text-gray-300">
                        <span className="text-purple-400">✓</span> {f}
                      </li>
                    ))}
                  </ul>
                  <button className={`w-full py-3 rounded-full font-bold transition ${plan.highlight ? "bg-purple-600 hover:bg-purple-700 text-white" : "bg-white/10 hover:bg-white/20 text-white"}`}>
                    Get Started
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {pricingTab === 'ecom' && (
          <div className="max-w-6xl mx-auto">
            <div className="flex justify-center mb-12">
              <div className="bg-white/10 rounded-full p-1 flex gap-1">
                {[{ key: 'monthly', label: 'Monthly' }, { key: 'sixmonths', label: '6 Months' }, { key: 'yearly', label: 'Yearly' }].map((option) => (
                  <button key={option.key} onClick={() => setEcomBilling(option.key)} className={`px-6 py-2.5 rounded-full font-semibold text-sm transition ${ecomBilling === option.key ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'}`}>
                    {option.label}
                    {option.key !== 'monthly' && <span className="ml-1.5 text-xs text-purple-300">{ecomSavings[option.key]}</span>}
                  </button>
                ))}
              </div>
            </div>
            <div className="grid md:grid-cols-3 gap-8">
              {ecomPlans.map((plan, i) => (
                <div key={i} className={`rounded-2xl p-8 border ${plan.highlight ? "border-purple-500 bg-purple-900/20" : "border-white/10 bg-white/5"}`}>
                  {plan.highlight && <div className="text-xs font-bold text-purple-400 mb-3 uppercase tracking-widest">Most Popular</div>}
                  <h3 className="text-2xl font-bold mb-1">{plan.name}</h3>
                  <p className="text-gray-400 text-sm mb-4">{plan.desc}</p>
                  <div className="text-5xl font-extrabold mb-1">
                    {getEcomPrice(plan)}<span className="text-lg text-gray-400">/mo</span>
                  </div>
                  {ecomBilling !== 'monthly' && (
                    <p className="text-purple-400 text-xs mb-6">{ecomBilling === 'sixmonths' ? 'Billed every 6 months' : 'Billed annually'}</p>
                  )}
                  <ul className="space-y-3 mb-8 mt-4">
                    {plan.features.map((f, j) => (
                      <li key={j} className="flex items-center gap-2 text-sm text-gray-300">
                        <span className="text-purple-400">✓</span> {f}
                      </li>
                    ))}
                  </ul>
                  <button className={`w-full py-3 rounded-full font-bold transition ${plan.highlight ? "bg-purple-600 hover:bg-purple-700 text-white" : "bg-white/10 hover:bg-white/20 text-white"}`}>
                    Get Started
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* FAQ */}
      <section id="faq" className="px-8 py-24 bg-white/5">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-4xl font-bold text-center mb-4">Frequently Asked Questions</h2>
          <p className="text-gray-400 text-center mb-16">Have more questions? Contact us at support@klipflowai.com</p>
          <div className="space-y-3">
            {faqs.map((item, i) => (
              <div key={i} className="border border-white/10 rounded-xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-white/5 transition"
                >
                  <span className="font-semibold text-sm">{item.q}</span>
                  <span className="text-purple-400 text-lg ml-4">{openFaq === i ? '−' : '+'}</span>
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-4 text-gray-400 text-sm leading-relaxed border-t border-white/5 pt-3">
                    {item.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FINAL CTA */}
      <section className="px-8 py-32 text-center">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-5xl font-extrabold mb-6">
            Your AI Employee is <span className="bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">Ready to Work.</span>
          </h2>
          <p className="text-gray-400 text-xl mb-10">25 free tokens. No credit card. No commitment. Pick your niche and let KlipflowAI do the rest.</p>
          <button className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-4 px-12 rounded-full text-lg transition">
            Sign Up Free →
          </button>
          <p className="text-gray-600 text-sm mt-4">Join creators and brands already using KlipflowAI</p>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-white/10 px-8 py-16">
        <div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-12">
          <div>
            <span className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">KlipflowAI</span>
            <p className="text-gray-500 text-sm mt-3 leading-relaxed">The only platform that spies, creates, and launches — all in one.</p>
            <div className="flex gap-3 mt-4">
              {["TikTok", "IG", "YT", "FB", "𝕏"].map((p, i) => (
                <div key={i} className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center text-xs text-gray-400 hover:bg-purple-600 hover:text-white transition cursor-pointer">{p}</div>
              ))}
            </div>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-4">Product</h4>
            <ul className="space-y-2 text-gray-500 text-sm">
              <li><a href="#features" className="hover:text-white transition">Features</a></li>
              <li><a href="#pricing" className="hover:text-white transition">Pricing</a></li>
              <li><a href="#" className="hover:text-white transition">Changelog</a></li>
              <li><a href="#" className="hover:text-white transition">Roadmap</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-4">Resources</h4>
            <ul className="space-y-2 text-gray-500 text-sm">
              <li><a href="#" className="hover:text-white transition">Blog</a></li>
              <li><a href="#" className="hover:text-white transition">Academy</a></li>
              <li><a href="#" className="hover:text-white transition">API Docs</a></li>
              <li><a href="#faq" className="hover:text-white transition">FAQ</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-4">Company</h4>
            <ul className="space-y-2 text-gray-500 text-sm">
              <li><a href="#" className="hover:text-white transition">About</a></li>
              <li><a href="#" className="hover:text-white transition">Contact</a></li>
              <li><a href="#" className="hover:text-white transition">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-white transition">Terms of Service</a></li>
            </ul>
          </div>
        </div>
        <div className="max-w-6xl mx-auto mt-12 pt-8 border-t border-white/10 text-center text-gray-600 text-sm">
          © 2026 KlipflowAI · All rights reserved
        </div>
      </footer>

    </main>
  );
}