import PSEOPage from "../components/PSEOPage";
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Ad Generator — Create High-Converting Video Ads',
  description: 'Generate scroll-stopping video ads with AI in minutes. Perfect for Facebook, TikTok, and Instagram. Turn any product into a winning video ad without a production team.',
  keywords: ['AI ad generator', 'AI video ad maker', 'Facebook video ad generator', 'TikTok ad generator', 'AI advertisement creator', 'video ad AI', 'product video ad generator'],
  alternates: { canonical: 'https://klipflowai.com/ai-ad-generator' },
  openGraph: {
    title: 'AI Ad Generator — High-Converting Video Ads | KlipflowAI',
    description: 'Generate scroll-stopping video ads with AI. For Facebook, TikTok, Instagram. No production team needed.',
    url: 'https://klipflowai.com/ai-ad-generator',
  },
}

export default function AIAdGenerator() {
  return (
    <PSEOPage
      badge="🎨 AI Ad Generator"
      title="Generate High-Converting Video & Image Ads with AI"
      subtitle="Inspired by winning formulas. Unique to your brand. Ready in minutes."
      description="KlipflowAI's AI Ad Generator creates professional video and image advertisements inspired by winning ad formulas in your market. Spy on what's working, generate a better version, and launch — all in one platform. Every ad is unique to your brand, compliant with platform policies, and optimized for maximum conversion performance."
      keywords={["ai ad generator", "ai advertisement generator", "ai video ad creator", "facebook ad generator ai", "ai ad maker", "generate ads with ai", "ai advertising tool", "automated ad creation"]}
      howItWorks={[
        { step: "1", icon: "🕵️", title: "Find Winning Ads", desc: "Use our Ad Spy tool to find what's working in your market. Ads running 7+ days are proven winners." },
        { step: "2", icon: "✨", title: "AI Generates Your Ad", desc: "One click to generate a unique video or image ad inspired by the winning formula." },
        { step: "3", icon: "🚀", title: "Download or Launch", desc: "Download your ad creative or launch it directly as a Facebook campaign with one more click." }
      ]}
      features={[
        { icon: "🎬", title: "Video Ads", desc: "Cinematic AI video ads in any format. Product focused, testimonial, UGC style, and more." },
        { icon: "🖼️", title: "Image Ads", desc: "High-quality static and animated image ads. Scroll-stopping visuals for feed and stories." },
        { icon: "🤝", title: "UGC Style Ads", desc: "Authentic testimonial-style ads with AI avatars. The highest converting ad format on social." },
        { icon: "📐", title: "All Ad Formats", desc: "Feed ads, story ads, reels ads, carousel ads. Every format for every placement." },
        { icon: "🎯", title: "Conversion Optimized", desc: "Every ad follows proven conversion frameworks — problem, agitation, solution, CTA." },
        { icon: "♾️", title: "Unlimited Variations", desc: "Generate multiple ad variations to A/B test. Find your winner faster with more creative options." }
      ]}
      faqs={[
        { q: "What types of ads can KlipflowAI generate?", a: "KlipflowAI generates video ads, image ads, UGC testimonial ads, and avatar spokesperson ads — for Facebook, Instagram, TikTok, YouTube, and more." },
        { q: "Are the ads unique to my brand?", a: "Yes. Every ad generated is completely unique. We use winning ad formulas as inspiration but generate entirely original content for your brand." },
        { q: "Can I use these ads on Facebook?", a: "Yes. All ads generated by KlipflowAI are compliant with Facebook and Instagram advertising policies. You own the creative and can run it anywhere." },
        { q: "How many ad variations can I generate?", a: "As many as your token balance allows. We recommend generating at least 3-5 variations per campaign to identify your best performer through A/B testing." },
        { q: "Can I launch ads directly from KlipflowAI?", a: "Yes. Pro and Agency plan users can launch Facebook ad campaigns directly from KlipflowAI using our One-Click Ad Launcher — no Facebook Ads Manager experience needed." }
      ]}
      ctaTitle="Generate Your First Ad Free"
      ctaDesc="25 free tokens on signup. Your ad ready in minutes."
    />
  );
}